version: "3.8"
services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - mongo
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
